# this is a workflow to remove all modules, be careful!

name: rmModules

on:
  # does not automatically get triggered!
  workflow_dispatch: # manually triggered

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: qoomon/actions--setup-git@v1
        with:
          user: bot
      - name: Nuke modules
        run: |
          echo "about to remove folders $(ls -d [0-9][0-9][0-9][0-9])"
          rm -Rf [0-9][0-9][0-9][0-9]
          git commit -m "nuked modules"
          git push
